/*
 * Copyright 2006 Sony Computer Entertainment Inc.
 *
 * Licensed under the SCEA Shared Source License, Version 1.0 (the "License"); you may not use this 
 * file except in compliance with the License. You may obtain a copy of the License at:
 * http://research.scea.com/scea_shared_source_license.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License 
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or 
 * implied. See the License for the specific language governing permissions and limitations under the 
 * License. 
 */

#ifndef __DOM_CONSTANTS_H__
#define __DOM_CONSTANTS_H__

#include <dae/daeDomTypes.h>

extern DLLSPEC daeString COLLADA_VERSION;
extern DLLSPEC daeString COLLADA_NAMESPACE;
extern DLLSPEC daeString COMMON_PROFILE_PROGRAMS_ANGLE_MAP;
extern DLLSPEC daeString COMMON_PROFILE_PROGRAMS_BEZIER;
extern DLLSPEC daeString COMMON_PROFILE_PROGRAMS_BSPLINE;
extern DLLSPEC daeString COMMON_PROFILE_PROGRAMS_CARDINAL;
extern DLLSPEC daeString COMMON_PROFILE_PROGRAMS_CONSTANT;
extern DLLSPEC daeString COMMON_PROFILE_PROGRAMS_CUBE_MAP;
extern DLLSPEC daeString COMMON_PROFILE_PROGRAMS_FISH_EYE;
extern DLLSPEC daeString COMMON_PROFILE_PROGRAMS_HERMITE;
extern DLLSPEC daeString COMMON_PROFILE_PROGRAMS_LAMBERT;
extern DLLSPEC daeString COMMON_PROFILE_PROGRAMS_LINEAR;
extern DLLSPEC daeString COMMON_PROFILE_PROGRAMS_ORTHOGRAPHIC;
extern DLLSPEC daeString COMMON_PROFILE_PROGRAMS_PANORAMA;
extern DLLSPEC daeString COMMON_PROFILE_PROGRAMS_PERSPECTIVE;
extern DLLSPEC daeString COMMON_PROFILE_PROGRAMS_PHONG;
extern DLLSPEC daeString COMMON_PROFILE_PROGRAMS_REAR_FISH_EYE;
extern DLLSPEC daeString COMMON_PROFILE_PROGRAMS_SPHERICAL;
extern DLLSPEC daeString COMMON_PROFILE_PROGRAMS_STEP;

extern DLLSPEC daeString COMMON_PROFILE_INPUT_BIND_SHAPE_NORMAL;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_BIND_SHAPE_POSITION;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_BINORMAL;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_COLOR;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_IMAGE;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_IN_TANGENT;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_INPUT;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_INTERPOLATION;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_INV_BIND_MATRIX;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_JOINT;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_JOINTS_AND_WEIGHTS;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_NORMAL;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_OUTPUT;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_OUT_TANGENT;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_POSITION;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_TANGENT;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_TEXCOORD;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_TEXTURE;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_UV;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_VERTEX;
extern DLLSPEC daeString COMMON_PROFILE_INPUT_WEIGHT;

extern DLLSPEC daeString COMMON_PROFILE_CODE_FRAGMENT_PROGRAM;
extern DLLSPEC daeString COMMON_PROFILE_CODE_VERTEX_PROGRAM;

extern DLLSPEC daeString COMMON_PROFILE_PARAM_A;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_AMBIENT;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_ANGLE;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_ATTENUATION;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_ATTENUATION_SCALE;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_B;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_BOTTOM;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_COLLOR;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_DIFFUSE;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_EMMISION;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_FALLOFF;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_FALLOFF_SCALE;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_G;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_LEFT;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_P;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_Q;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_R;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_REFLECTIVE;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_REFLECTIVITY;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_RIGHT;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_S;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_SHININESS;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_SPECULAR;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_T;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_TIME;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_TOP;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_TRANSPARENCY;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_TRANSPARENT;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_U;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_V;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_W;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_X;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_XFOV;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_Y;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_YFOV;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_Z;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_ZFAR;
extern DLLSPEC daeString COMMON_PROFILE_PARAM_ZNEAR;


extern DLLSPEC daeString COLLADA_TYPE_COLLADA;
extern DLLSPEC daeString COLLADA_TYPE_ACCESSOR;
extern DLLSPEC daeString COLLADA_TYPE_ARRAY;
extern DLLSPEC daeString COLLADA_TYPE_FLOAT_ARRAY;
extern DLLSPEC daeString COLLADA_TYPE_INT_ARRAY;
extern DLLSPEC daeString COLLADA_TYPE_NAME_ARRAY;
extern DLLSPEC daeString COLLADA_TYPE_BOOL_ARRAY;
extern DLLSPEC daeString COLLADA_TYPE_INPUT;
extern DLLSPEC daeString COLLADA_TYPE_PARAM;
extern DLLSPEC daeString COLLADA_TYPE_SOURCE;
extern DLLSPEC daeString COLLADA_TYPE_TECHNIQUE;
extern DLLSPEC daeString COLLADA_TYPE_MESH;
extern DLLSPEC daeString COLLADA_TYPE_COMBINER;
extern DLLSPEC daeString COLLADA_TYPE_V;
extern DLLSPEC daeString COLLADA_TYPE_JOINTS;
extern DLLSPEC daeString COLLADA_TYPE_LINES;
extern DLLSPEC daeString COLLADA_TYPE_P;
extern DLLSPEC daeString COLLADA_TYPE_LINESTRIPS;
extern DLLSPEC daeString COLLADA_TYPE_POLYGONS;
extern DLLSPEC daeString COLLADA_TYPE_H;
extern DLLSPEC daeString COLLADA_TYPE_TRIANGLES;
extern DLLSPEC daeString COLLADA_TYPE_TRIFANS;
extern DLLSPEC daeString COLLADA_TYPE_TRISTRIPS;
extern DLLSPEC daeString COLLADA_TYPE_VERTICES;
extern DLLSPEC daeString COLLADA_TYPE_LOOKAT;
extern DLLSPEC daeString COLLADA_TYPE_MATRIX;
extern DLLSPEC daeString COLLADA_TYPE_PERSPECTIVE;
extern DLLSPEC daeString COLLADA_TYPE_ROTATE;
extern DLLSPEC daeString COLLADA_TYPE_SCALE;
extern DLLSPEC daeString COLLADA_TYPE_SKEW;
extern DLLSPEC daeString COLLADA_TYPE_TRANSLATE;
extern DLLSPEC daeString COLLADA_TYPE_IMAGE;
extern DLLSPEC daeString COLLADA_TYPE_LIGHT;
extern DLLSPEC daeString COLLADA_TYPE_MATERIAL;
extern DLLSPEC daeString COLLADA_TYPE_PASS;
extern DLLSPEC daeString COLLADA_TYPE_SHADER;
extern DLLSPEC daeString COLLADA_TYPE_TEXTURE;
extern DLLSPEC daeString COLLADA_TYPE_CODE;
extern DLLSPEC daeString COLLADA_TYPE_ENTRY;
extern DLLSPEC daeString COLLADA_TYPE_PROGRAM;
extern DLLSPEC daeString COLLADA_TYPE_CAMERA;
extern DLLSPEC daeString COLLADA_TYPE_OPTICS;
extern DLLSPEC daeString COLLADA_TYPE_IMAGER;
extern DLLSPEC daeString COLLADA_TYPE_INSTANCE;
extern DLLSPEC daeString COLLADA_TYPE_CHANNEL;
extern DLLSPEC daeString COLLADA_TYPE_SAMPLER;
extern DLLSPEC daeString COLLADA_TYPE_SKIN;
extern DLLSPEC daeString COLLADA_TYPE_ASSET;
extern DLLSPEC daeString COLLADA_TYPE_AUTHOR;
extern DLLSPEC daeString COLLADA_TYPE_AUTHORING_TOOL;
extern DLLSPEC daeString COLLADA_TYPE_CREATED;
extern DLLSPEC daeString COLLADA_TYPE_MODIFIED;
extern DLLSPEC daeString COLLADA_TYPE_REVISION;
extern DLLSPEC daeString COLLADA_TYPE_SOURCE_DATA;
extern DLLSPEC daeString COLLADA_TYPE_COPYRIGHT;
extern DLLSPEC daeString COLLADA_TYPE_TITLE;
extern DLLSPEC daeString COLLADA_TYPE_SUBJECT;
extern DLLSPEC daeString COLLADA_TYPE_KEYWORDS;
extern DLLSPEC daeString COLLADA_TYPE_COMMENTS;
extern DLLSPEC daeString COLLADA_TYPE_UP_AXIS;
extern DLLSPEC daeString COLLADA_TYPE_UNIT;
extern DLLSPEC daeString COLLADA_TYPE_EXTRA;
extern DLLSPEC daeString COLLADA_TYPE_BOUNDINGBOX;
extern DLLSPEC daeString COLLADA_TYPE_MIN;
extern DLLSPEC daeString COLLADA_TYPE_MAX;
extern DLLSPEC daeString COLLADA_TYPE_NODE;
extern DLLSPEC daeString COLLADA_TYPE_SCENE;
extern DLLSPEC daeString COLLADA_TYPE_ANIMATION;
extern DLLSPEC daeString COLLADA_TYPE_CONTROLLER;
extern DLLSPEC daeString COLLADA_TYPE_GEOMETRY;
extern DLLSPEC daeString COLLADA_TYPE_LIBRARY;

extern DLLSPEC daeString COLLADA_ELEMENT_COLLADA;
extern DLLSPEC daeString COLLADA_ELEMENT_ASSET;
extern DLLSPEC daeString COLLADA_ELEMENT_LIBRARY;
extern DLLSPEC daeString COLLADA_ELEMENT_SCENE;
extern DLLSPEC daeString COLLADA_ELEMENT_PARAM;
extern DLLSPEC daeString COLLADA_ELEMENT_ARRAY;
extern DLLSPEC daeString COLLADA_ELEMENT_BOOL_ARRAY;
extern DLLSPEC daeString COLLADA_ELEMENT_FLOAT_ARRAY;
extern DLLSPEC daeString COLLADA_ELEMENT_INT_ARRAY;
extern DLLSPEC daeString COLLADA_ELEMENT_NAME_ARRAY;
extern DLLSPEC daeString COLLADA_ELEMENT_TECHNIQUE;
extern DLLSPEC daeString COLLADA_ELEMENT_ACCESSOR;
extern DLLSPEC daeString COLLADA_ELEMENT_COMBINER;
extern DLLSPEC daeString COLLADA_ELEMENT_JOINTS;
extern DLLSPEC daeString COLLADA_ELEMENT_PROGRAM;
extern DLLSPEC daeString COLLADA_ELEMENT_SOURCE;
extern DLLSPEC daeString COLLADA_ELEMENT_VERTICES;
extern DLLSPEC daeString COLLADA_ELEMENT_LINES;
extern DLLSPEC daeString COLLADA_ELEMENT_LINESTRIPS;
extern DLLSPEC daeString COLLADA_ELEMENT_POLYGONS;
extern DLLSPEC daeString COLLADA_ELEMENT_TRIANGLES;
extern DLLSPEC daeString COLLADA_ELEMENT_TRIFANS;
extern DLLSPEC daeString COLLADA_ELEMENT_TRISTRIPS;
extern DLLSPEC daeString COLLADA_ELEMENT_INPUT;
extern DLLSPEC daeString COLLADA_ELEMENT_V;
extern DLLSPEC daeString COLLADA_ELEMENT_P;
extern DLLSPEC daeString COLLADA_ELEMENT_H;
extern DLLSPEC daeString COLLADA_ELEMENT_SHADER;
extern DLLSPEC daeString COLLADA_ELEMENT_PASS;
extern DLLSPEC daeString COLLADA_ELEMENT_ENTRY;
extern DLLSPEC daeString COLLADA_ELEMENT_CODE;
extern DLLSPEC daeString COLLADA_ELEMENT_OPTICS;
extern DLLSPEC daeString COLLADA_ELEMENT_IMAGER;
extern DLLSPEC daeString COLLADA_ELEMENT_AUTHOR;
extern DLLSPEC daeString COLLADA_ELEMENT_AUTHORING_TOOL;
extern DLLSPEC daeString COLLADA_ELEMENT_CREATED;
extern DLLSPEC daeString COLLADA_ELEMENT_MODIFIED;
extern DLLSPEC daeString COLLADA_ELEMENT_REVISION;
extern DLLSPEC daeString COLLADA_ELEMENT_SOURCE_DATA;
extern DLLSPEC daeString COLLADA_ELEMENT_COPYRIGHT;
extern DLLSPEC daeString COLLADA_ELEMENT_TITLE;
extern DLLSPEC daeString COLLADA_ELEMENT_SUBJECT;
extern DLLSPEC daeString COLLADA_ELEMENT_KEYWORDS;
extern DLLSPEC daeString COLLADA_ELEMENT_COMMENTS;
extern DLLSPEC daeString COLLADA_ELEMENT_UP_AXIS;
extern DLLSPEC daeString COLLADA_ELEMENT_UNIT;
extern DLLSPEC daeString COLLADA_ELEMENT_MIN;
extern DLLSPEC daeString COLLADA_ELEMENT_MAX;
extern DLLSPEC daeString COLLADA_ELEMENT_LOOKAT;
extern DLLSPEC daeString COLLADA_ELEMENT_MATRIX;
extern DLLSPEC daeString COLLADA_ELEMENT_PERSPECTIVE;
extern DLLSPEC daeString COLLADA_ELEMENT_ROTATE;
extern DLLSPEC daeString COLLADA_ELEMENT_SCALE;
extern DLLSPEC daeString COLLADA_ELEMENT_SKEW;
extern DLLSPEC daeString COLLADA_ELEMENT_TRANSLATE;
extern DLLSPEC daeString COLLADA_ELEMENT_BOUNDINGBOX;
extern DLLSPEC daeString COLLADA_ELEMENT_INSTANCE;
extern DLLSPEC daeString COLLADA_ELEMENT_NODE;
extern DLLSPEC daeString COLLADA_ELEMENT_EXTRA;
extern DLLSPEC daeString COLLADA_ELEMENT_SAMPLER;
extern DLLSPEC daeString COLLADA_ELEMENT_CHANNEL;
extern DLLSPEC daeString COLLADA_ELEMENT_SKIN;
extern DLLSPEC daeString COLLADA_ELEMENT_MESH;
extern DLLSPEC daeString COLLADA_ELEMENT_ANIMATION;
extern DLLSPEC daeString COLLADA_ELEMENT_CAMERA;
extern DLLSPEC daeString COLLADA_ELEMENT_CONTROLLER;
extern DLLSPEC daeString COLLADA_ELEMENT_GEOMETRY;
extern DLLSPEC daeString COLLADA_ELEMENT_IMAGE;
extern DLLSPEC daeString COLLADA_ELEMENT_LIGHT;
extern DLLSPEC daeString COLLADA_ELEMENT_MATERIAL;
extern DLLSPEC daeString COLLADA_ELEMENT_TEXTURE;

#endif //__DOM_CONSTANTS_H__

