/*
 * Copyright 2006 Sony Computer Entertainment Inc.
 *
 * Licensed under the SCEA Shared Source License, Version 1.0 (the "License"); you may not use this 
 * file except in compliance with the License. You may obtain a copy of the License at:
 * http://research.scea.com/scea_shared_source_license.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License 
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or 
 * implied. See the License for the specific language governing permissions and limitations under the 
 * License. 
 */

#ifndef INTEGRATIONFULL_HEADER
#define INTEGRATIONFULL_HEADER

#include "intFx_sampler1D_common.h"
#include "intFx_sampler2D_common.h"
#include "intFx_sampler3D_common.h"
#include "intFx_samplerCUBE_common.h"
#include "intFx_colortarget_common.h"
#include "intFx_depthstenciltarget_common.h"
#include "intFx_clearcolor_common.h"
#include "intFx_cleardepth_common.h"
#include "intFx_clearstencil_common.h"
#include "intFx_annotate_common.h"
#include "intFx_code_common.h"
#include "intFx_newparam_common.h"
#include "intFx_setparam_common.h"
#include "intFx_code_profile.h"
#include "intFx_technique.h"
#include "intGl_sampler1D.h"
#include "intGl_sampler2D.h"
#include "intGl_sampler3D.h"
#include "intGl_samplerCUBE.h"
#include "intGl_samplerRECT.h"
#include "intGl_newparam.h"
#include "intGl_setparam.h"
#include "intGl_surface.h"
#include "intGl_shader.h"
#include "intGl_pass.h"
#include "intGl_profile.h"
#include "intCg_samplerRECT.h"
#include "intCg_connectparam.h"
#include "intCg_newarray_type.h"
#include "intCg_setarray_type.h"
#include "intCg_setuser_type.h"
#include "intCg_newparam.h"
#include "intCg_setparam.h"
#include "intCg_surface.h"
#include "intCg_shader.h"
#include "intCg_pass.h"
#include "intCg_profile.h"
#include "intMultiRepElement.h"
#include "intFx_basic_type_common.h"
#include "intFx_annotate_type_common.h"
#include "intFx_param_type_common.h"
#include "intGl_pipeline_settings.h"
#include "intCg_param_type.h"
#include "intCOLLADA.h"
#include "intAccessor.h"
#include "intArray.h"
#include "intFloat_array.h"
#include "intInt_array.h"
#include "intName_array.h"
#include "intBool_array.h"
#include "intInput.h"
#include "intParam.h"
#include "intSource.h"
#include "intMesh.h"
#include "intCombiner.h"
#include "intJoints.h"
#include "intLines.h"
#include "intLinestrips.h"
#include "intPolygons.h"
#include "intTriangles.h"
#include "intTrifans.h"
#include "intTristrips.h"
#include "intVertices.h"
#include "intLookat.h"
#include "intMatrix.h"
#include "intPerspective.h"
#include "intRotate.h"
#include "intScale.h"
#include "intSkew.h"
#include "intTranslate.h"
#include "intImage.h"
#include "intLight.h"
#include "intMaterial.h"
#include "intPass.h"
#include "intShader.h"
#include "intTexture.h"
#include "intCode.h"
#include "intEntry.h"
#include "intProgram.h"
#include "intCamera.h"
#include "intInstance.h"
#include "intChannel.h"
#include "intSampler.h"
#include "intSkin.h"
#include "intAsset.h"
#include "intExtra.h"
#include "intBoundingbox.h"
#include "intNode.h"
#include "intScene.h"
#include "intAnimation.h"
#include "intController.h"
#include "intGeometry.h"
#include "intLibrary.h"
#include "intFx_profile_abstract.h"
#include "intEffect.h"
#include "intProfile_GLSL.h"
#include "intProfile_CG.h"
#include "intBox.h"
#include "intPlane.h"
#include "intSphere.h"
#include "intEllipsoid.h"
#include "intCapsule.h"
#include "intCylinder.h"
#include "intConvex_mesh.h"
#include "intPhysics_material.h"
#include "intRigidbody.h"
#include "intShape.h"
#include "intForce_field.h"
#include "intPhysics_environment.h"
#include "intRigid_constraint.h"

void intRegisterElements();

#endif
