/*
 * Copyright 2006 Sony Computer Entertainment Inc.
 *
 * Licensed under the SCEA Shared Source License, Version 1.0 (the "License"); you may not use this 
 * file except in compliance with the License. You may obtain a copy of the License at:
 * http://research.scea.com/scea_shared_source_license.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License 
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or 
 * implied. See the License for the specific language governing permissions and limitations under the 
 * License. 
 */

#include <dom/domConstants.h>

daeString COLLADA_VERSION = "1.3.1";
daeString COLLADA_NAMESPACE = "http://www.collada.org/2005/COLLADASchema";

daeString COMMON_PROFILE_PROGRAMS_ANGLE_MAP = "ANGLE_MAP";
daeString COMMON_PROFILE_PROGRAMS_BEZIER = "BEZIER";
daeString COMMON_PROFILE_PROGRAMS_BSPLINE = "BSPLINE";
daeString COMMON_PROFILE_PROGRAMS_CARDINAL = "CARDINAL";
daeString COMMON_PROFILE_PROGRAMS_CONSTANT = "CONSTANT";
daeString COMMON_PROFILE_PROGRAMS_CUBE_MAP = "CUBE_MAP";
daeString COMMON_PROFILE_PROGRAMS_FISH_EYE = "FISH_EYE";
daeString COMMON_PROFILE_PROGRAMS_HERMITE = "HERMITE";
daeString COMMON_PROFILE_PROGRAMS_LAMBERT = "LAMBERT";
daeString COMMON_PROFILE_PROGRAMS_LINEAR = "LINEAR";
daeString COMMON_PROFILE_PROGRAMS_ORTHOGRAPHIC = "ORTHOGRAPHIC";
daeString COMMON_PROFILE_PROGRAMS_PANORAMA = "PANORAMA";
daeString COMMON_PROFILE_PROGRAMS_PERSPECTIVE = "PERSPECTIVE";
daeString COMMON_PROFILE_PROGRAMS_PHONG = "PHONG";
daeString COMMON_PROFILE_PROGRAMS_REAR_FISH_EYE = "REAR_FISH_EYE";
daeString COMMON_PROFILE_PROGRAMS_SPHERICAL = "SPHERICAL";
daeString COMMON_PROFILE_PROGRAMS_STEP = "STEP";

daeString COMMON_PROFILE_INPUT_BIND_SHAPE_NORMAL = "BIND_SHAPE_NORMAL";
daeString COMMON_PROFILE_INPUT_BIND_SHAPE_POSITION = "BIND_SHAPE_POSITION";
daeString COMMON_PROFILE_INPUT_BINORMAL = "BINORMAL";
daeString COMMON_PROFILE_INPUT_COLOR = "COLOR";
daeString COMMON_PROFILE_INPUT_IMAGE = "IMAGE";
daeString COMMON_PROFILE_INPUT_IN_TANGENT = "IN_TANGENT";
daeString COMMON_PROFILE_INPUT_INPUT = "INPUT";
daeString COMMON_PROFILE_INPUT_INTERPOLATION = "INTERPOLATION";
daeString COMMON_PROFILE_INPUT_INV_BIND_MATRIX = "INV_BIND_MATRIX";
daeString COMMON_PROFILE_INPUT_JOINT = "JOINT";
daeString COMMON_PROFILE_INPUT_JOINTS_AND_WEIGHTS = "JOINTS_AND_WEIGHTS";
daeString COMMON_PROFILE_INPUT_NORMAL = "NORMAL";
daeString COMMON_PROFILE_INPUT_OUTPUT = "OUTPUT";
daeString COMMON_PROFILE_INPUT_OUT_TANGENT = "OUT_TANGENT";
daeString COMMON_PROFILE_INPUT_POSITION = "POSITION";
daeString COMMON_PROFILE_INPUT_TANGENT = "TANGENT";
daeString COMMON_PROFILE_INPUT_TEXCOORD = "TEXCOORD";
daeString COMMON_PROFILE_INPUT_TEXTURE = "TEXTURE";
daeString COMMON_PROFILE_INPUT_UV = "UV";
daeString COMMON_PROFILE_INPUT_VERTEX = "VERTEX";
daeString COMMON_PROFILE_INPUT_WEIGHT = "WEIGHT";

daeString COMMON_PROFILE_CODE_FRAGMENT_PROGRAM = "FRAGMENT_PROGRAM";
daeString COMMON_PROFILE_CODE_VERTEX_PROGRAM = "VERTEX_PROGRAM";

daeString COMMON_PROFILE_PARAM_A = "A";
daeString COMMON_PROFILE_PARAM_AMBIENT = "AMBIENT";
daeString COMMON_PROFILE_PARAM_ANGLE = "ANGLE";
daeString COMMON_PROFILE_PARAM_ATTENUATION = "ATTENUATION";
daeString COMMON_PROFILE_PARAM_ATTENUATION_SCALE = "ATTENUATION_SCALE";
daeString COMMON_PROFILE_PARAM_B = "B";
daeString COMMON_PROFILE_PARAM_BOTTOM = "BOTTOM";
daeString COMMON_PROFILE_PARAM_COLLOR = "COLLOR";
daeString COMMON_PROFILE_PARAM_DIFFUSE = "DIFFUSE";
daeString COMMON_PROFILE_PARAM_EMMISION = "EMMISION";
daeString COMMON_PROFILE_PARAM_FALLOFF = "FALLOFF";
daeString COMMON_PROFILE_PARAM_FALLOFF_SCALE = "FALLOFF_SCALE";
daeString COMMON_PROFILE_PARAM_G = "G";
daeString COMMON_PROFILE_PARAM_LEFT = "LEFT";
daeString COMMON_PROFILE_PARAM_P = "P";
daeString COMMON_PROFILE_PARAM_Q = "Q";
daeString COMMON_PROFILE_PARAM_R = "R";
daeString COMMON_PROFILE_PARAM_REFLECTIVE = "REFLECTIVE";
daeString COMMON_PROFILE_PARAM_REFLECTIVITY = "REFLECTIVITY";
daeString COMMON_PROFILE_PARAM_RIGHT = "RIGHT";
daeString COMMON_PROFILE_PARAM_S = "S";
daeString COMMON_PROFILE_PARAM_SHININESS = "SHININESS";
daeString COMMON_PROFILE_PARAM_SPECULAR = "SPECULAR";
daeString COMMON_PROFILE_PARAM_T = "T";
daeString COMMON_PROFILE_PARAM_TIME = "TIME";
daeString COMMON_PROFILE_PARAM_TOP = "TOP";
daeString COMMON_PROFILE_PARAM_TRANSPARENCY = "TRANSPARENCY";
daeString COMMON_PROFILE_PARAM_TRANSPARENT = "TRANSPARENT";
daeString COMMON_PROFILE_PARAM_U = "U";
daeString COMMON_PROFILE_PARAM_V = "V";
daeString COMMON_PROFILE_PARAM_W = "W";
daeString COMMON_PROFILE_PARAM_X = "X";
daeString COMMON_PROFILE_PARAM_XFOV = "XFOV";
daeString COMMON_PROFILE_PARAM_Y = "Y";
daeString COMMON_PROFILE_PARAM_YFOV = "YFOV";
daeString COMMON_PROFILE_PARAM_Z = "Z";
daeString COMMON_PROFILE_PARAM_ZFAR = "ZFAR";
daeString COMMON_PROFILE_PARAM_ZNEAR = "ZNEAR";

daeString COLLADA_ELEMENT_COLLADA = "COLLADA";
daeString COLLADA_ELEMENT_ACCESSOR = "accessor";
daeString COLLADA_ELEMENT_ARRAY = "array";
daeString COLLADA_ELEMENT_FLOAT_ARRAY = "float_array";
daeString COLLADA_ELEMENT_INT_ARRAY = "int_array";
daeString COLLADA_ELEMENT_NAME_ARRAY = "Name_array";
daeString COLLADA_ELEMENT_BOOL_ARRAY = "bool_array";
daeString COLLADA_ELEMENT_INPUT = "input";
daeString COLLADA_ELEMENT_PARAM = "param";
daeString COLLADA_ELEMENT_SOURCE = "source";
daeString COLLADA_ELEMENT_TECHNIQUE = "technique";
daeString COLLADA_ELEMENT_MESH = "mesh";
daeString COLLADA_ELEMENT_COMBINER = "combiner";
daeString COLLADA_ELEMENT_V = "v";
daeString COLLADA_ELEMENT_JOINTS = "joints";
daeString COLLADA_ELEMENT_LINES = "lines";
daeString COLLADA_ELEMENT_P = "p";
daeString COLLADA_ELEMENT_LINESTRIPS = "linestrips";
daeString COLLADA_ELEMENT_POLYGONS = "polygons";
daeString COLLADA_ELEMENT_H = "h";
daeString COLLADA_ELEMENT_TRIANGLES = "triangles";
daeString COLLADA_ELEMENT_TRIFANS = "trifans";
daeString COLLADA_ELEMENT_TRISTRIPS = "tristrips";
daeString COLLADA_ELEMENT_VERTICES = "vertices";
daeString COLLADA_ELEMENT_LOOKAT = "lookat";
daeString COLLADA_ELEMENT_MATRIX = "matrix";
daeString COLLADA_ELEMENT_PERSPECTIVE = "perspective";
daeString COLLADA_ELEMENT_ROTATE = "rotate";
daeString COLLADA_ELEMENT_SCALE = "scale";
daeString COLLADA_ELEMENT_SKEW = "skew";
daeString COLLADA_ELEMENT_TRANSLATE = "translate";
daeString COLLADA_ELEMENT_IMAGE = "image";
daeString COLLADA_ELEMENT_LIGHT = "light";
daeString COLLADA_ELEMENT_MATERIAL = "material";
daeString COLLADA_ELEMENT_PASS = "pass";
daeString COLLADA_ELEMENT_SHADER = "shader";
daeString COLLADA_ELEMENT_TEXTURE = "texture";
daeString COLLADA_ELEMENT_CODE = "code";
daeString COLLADA_ELEMENT_ENTRY = "entry";
daeString COLLADA_ELEMENT_PROGRAM = "program";
daeString COLLADA_ELEMENT_CAMERA = "camera";
daeString COLLADA_ELEMENT_OPTICS = "optics";
daeString COLLADA_ELEMENT_IMAGER = "imager";
daeString COLLADA_ELEMENT_INSTANCE = "instance";
daeString COLLADA_ELEMENT_CHANNEL = "channel";
daeString COLLADA_ELEMENT_SAMPLER = "sampler";
daeString COLLADA_ELEMENT_SKIN = "skin";
daeString COLLADA_ELEMENT_ASSET = "asset";
daeString COLLADA_ELEMENT_AUTHOR = "author";
daeString COLLADA_ELEMENT_AUTHORING_TOOL = "authoring_tool";
daeString COLLADA_ELEMENT_CREATED = "created";
daeString COLLADA_ELEMENT_MODIFIED = "modified";
daeString COLLADA_ELEMENT_REVISION = "revision";
daeString COLLADA_ELEMENT_SOURCE_DATA = "source_data";
daeString COLLADA_ELEMENT_COPYRIGHT = "copyright";
daeString COLLADA_ELEMENT_TITLE = "title";
daeString COLLADA_ELEMENT_SUBJECT = "subject";
daeString COLLADA_ELEMENT_KEYWORDS = "keywords";
daeString COLLADA_ELEMENT_COMMENTS = "comments";
daeString COLLADA_ELEMENT_UP_AXIS = "up_axis";
daeString COLLADA_ELEMENT_UNIT = "unit";
daeString COLLADA_ELEMENT_EXTRA = "extra";
daeString COLLADA_ELEMENT_BOUNDINGBOX = "boundingbox";
daeString COLLADA_ELEMENT_MIN = "min";
daeString COLLADA_ELEMENT_MAX = "max";
daeString COLLADA_ELEMENT_NODE = "node";
daeString COLLADA_ELEMENT_SCENE = "scene";
daeString COLLADA_ELEMENT_ANIMATION = "animation";
daeString COLLADA_ELEMENT_CONTROLLER = "controller";
daeString COLLADA_ELEMENT_GEOMETRY = "geometry";
daeString COLLADA_ELEMENT_LIBRARY = "library";
